#!/usr/bin/env bash
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ELF="${1:-$REPO_DIR/build/ProcHMI.elf}"
OUT_DIR="$REPO_DIR/208_source/modules/ProcHMI/decompiled"

TEXT_START=$((0x1050))
TEXT_END=$((0x9A8778))
CHUNK_SIZE=$((0x80000))  # 512 KB per chunk

mkdir -p "$OUT_DIR"

addr=$TEXT_START
chunk=0
while [ "$addr" -lt "$TEXT_END" ]; do
    end=$((addr + CHUNK_SIZE))
    if [ "$end" -gt "$TEXT_END" ]; then
        end=$TEXT_END
    fi

    start_hex=$(printf "0x%x" "$addr")
    end_hex=$(printf "0x%x" "$end")
    chunk_name=$(printf "chunk_%03d" "$chunk")
    outfile="$OUT_DIR/${chunk_name}.c"

    if [ -f "$outfile" ]; then
        echo "[$chunk_name] $start_hex-$end_hex already exists, skipping"
    else
        echo "[$chunk_name] Decompiling $start_hex - $end_hex ..."
        retdec-decompiler "$ELF" \
            -o "$outfile" \
            --select-ranges "${start_hex}-${end_hex}" \
            --select-decode-only \
            --cleanup \
            2>&1 | tail -5
        echo "[$chunk_name] Done -> $(wc -l < "$outfile") lines"
    fi

    addr=$end
    chunk=$((chunk + 1))
done

echo ""
echo "=== All chunks complete ==="
echo "Combining into ProcHMI.c ..."

{
    echo "//"
    echo "// ProcHMI.c - Decompiled from ProcHMI.elf (Opel Navi 600/900)"
    echo "// Generated by retdec in chunked mode"
    echo "// Text section: $(printf '0x%x' $TEXT_START) - $(printf '0x%x' $TEXT_END)"
    echo "//"
    echo ""
    echo "#include <stdbool.h>"
    echo "#include <stdint.h>"
    echo "#include <stdlib.h>"
    echo ""

    for f in "$OUT_DIR"/chunk_*.c; do
        bn=$(basename "$f" .c)
        echo ""
        echo "// ============================================"
        echo "// $bn"
        echo "// ============================================"
        echo ""
        # Skip headers/includes from individual chunks, keep function bodies
        awk '
            BEGIN { in_body=0 }
            /^\/\/ -+ Function/ { in_body=1 }
            /^\/\/ Address range:/ { in_body=1 }
            in_body { print }
        ' "$f"
    done
} > "$OUT_DIR/ProcHMI.c"

total_lines=$(wc -l < "$OUT_DIR/ProcHMI.c")
echo "Combined output: $OUT_DIR/ProcHMI.c ($total_lines lines)"
echo ""
echo "Cleaning up chunk files..."
rm -f "$OUT_DIR"/chunk_*.c
echo "Done!"
